build:
    requirements: {}
dependencies: {}
sources:
    fac_data:
        description: A list of all dialysis facilities registered with Medicare that
            includes addresses and phone numbers, as well as services and quality
            of care provided.
        file: DFC_SOCRATA_FAC_DATA
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
    national_data:
        description: National averages of common dialysis quality measures.
        file: DFC_SOCRATA_NATIONAL_DATA
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
    qip_data:
        description: 'The data set includes the number of eligible patients by clinical
            measure; % patients with Hemoglobin > 12; ESRD QIP data by facility: %
            of hemodialysis patient-months with spKt/V >= 1.2; % of peritoneal patient-months
            with Kt/V >= 1.7 Kt/V (dialytic + residual) during the four-month study
            period; % of pediatric in-center hemodialysis patient-months with spKt/V
            >= 1.2; % of hemodialysis patients using an arteriovenous fistula during
            last treatment of the month; % of hemodialysis patients using an intravenous
            catheter during the last treatment of the month and for at least 89 days
            prior; Hemoglobin > 12 measure score; Dialysis Adequacy Measure Topic
            score; Vascular Access Type Measure Topic score; ICH CAHPS Admin score;
            NHSN Event Reporting score; Mineral Metabolism Reporting score; Anemia
            Management Reporting score; the Total Performance Score; and payment reduction
            percentage.'
        file: PY2015
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
    state_data:
        description: State averages of common dialysis quality measures.
        file: DFC_SOCRATA_STATE_DATA
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
views: {}
