build:
    requirements: {}
dependencies: {}
sources:
    fac_data:
        description: Facilities
        file: DFC_SOCRATA_FAC_DATA
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
    national_data:
        description: description
        file: DFC_SOCRATA_NATIONAL_DATA
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
    qip_data:
        description: description
        file: PY2015
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
    state_data:
        description: description
        file: DFC_SOCRATA_STATE_DATA
        filetype: csv
        url: https://data.medicare.gov/views/bg9k-emty/files/qUrdPCwgdv-H4tocW1m_6PtReuPSzyJHioinJ0_UkdI?filename=DFCompare_Revised_FlatFiles.zip
        urlfiletype: zip
views: {}
